### ISSUE TITLE
Need to throw appropriate exception for larger paintings in main.py line 190

### ISSUE THREAD

**Issue by acupoftee** [bethyd/abstractGAN#1]
`torchvision` has the appropriate tools to handle scaling, resizing, and cropping images for training deep learning models. While it's able to train abstractGAN with some genres, it throws the following error with others, like "cityscape" for example"

`Traceback (most recent call last):
  File "main2.py", line 190, in <module>
    for i, data in enumerate(dataloader, 0):
  File "/home/bethy/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 187, in __next__
    return self._process_next_batch(batch)
  File "/home/bethy/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
OSError: Traceback (most recent call last):
  File "/home/bethy/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/bethy/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 40, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/folder.py", line 116, in __getitem__
    img = self.loader(path)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/folder.py", line 63, in default_loader
    return pil_loader(path)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/folder.py", line 46, in pil_loader
    return img.convert('RGB')
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 857, in convert
    self.load()
  File "/usr/lib/python3/dist-packages/PIL/ImageFile.py", line 231, in load
    "(%d bytes not processed)" % len(b))
OSError: image file is truncated (54 bytes not processed)
`

**Comment by bethyd** [comment]
The error's been solved by adding the following statement before the code block at line 190:
'
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
`

**Comment by acupoftee** [comment]
The error's been solved by adding the following statement before the code block at line 190:

```
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
The quality of the training images and generated images haven't been effected either
